[#m8xpmt] Create Navbar
allispeck/pupdates-app pull request #8
Opened 2021-02-05 23:47 UTC by allispeck

most styles applied, mobile responsive.

2021-02-05 23:50 UTC, BrayonCrayon requested changes

2021-02-05 23:50 UTC, BrayonCrayon commented on public/index.html
> +    <link rel="stylesheet" href="/"
Could we remove this tag?

2021-02-05 23:50 UTC, BrayonCrayon commented
Good work!

2021-02-07 01:22 UTC, allispeck commented
removed it!

2021-11-30 14:27 UTC, BrayonCrayon commented on src/layout/Navbar.js
> +    let w = document.documentElement.clientWidth || window.innerWidth;
@allispeck, can we use Tailwindcss's css breakpoints instead? Might run into some issues later on that could impact how you would construct your components :)
https://tailwindcss.com/docs/responsive-design

2022-03-22 23:08 UTC, BrayonCrayon commented on src/layout/Navbar.js
> +    let w = document.documentElement.clientWidth || window.innerWidth;
Awesome!

2022-03-22 23:09 UTC, BrayonCrayon approved these changes

2022-03-22 23:31 UTC, merged